apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-boot-crac-demo
  name: spring-boot-crac-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-boot-crac-demo
  sessionAffinity: None
  type: NodePort
